name: dental_clinic_app
description: A modern dental clinic management Flutter application.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  uuid: ^4.2.1
  collection: ^1.18.0
  intl: ^0.19.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  path: ^1.9.0

  # For local persistence (simple) - using shared_preferences for prototype
  shared_preferences: ^2.3.2

  # For multi_select widgets
  multi_select_flutter: ^4.1.3

  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/consent/
    - assets/lab/
