name: dental_clinic_app
description: A modern dental clinic management Flutter application.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  firebase_core: 4.1.1
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  uuid: ^4.2.1
  collection: ^1.18.0
  intl: ^0.19.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  path: ^1.9.0
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  open_filex: ^4.3.4
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  http: ^1.2.2

  # For local persistence (simple) - using shared_preferences for prototype
  shared_preferences: ^2.3.2

  # For multi_select widgets
  multi_select_flutter: ^4.1.3

  flutter_svg: ^2.0.9
  url_launcher: ^6.2.6
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
